---
name: Games-Risk
version: 0.3.2
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: classical 'risk' board game
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Class::Accessor::Fast: 0
  File::Basename: 0
  Image::Size: 0
  List::Util: 0
  Module::Util: 0
  POE: 0
  Readonly: 0
  Tk: 0
  Tk::Balloon: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  UNIVERSAL::require: 0
  aliased: 0
  perl: 5.010
build_requires:
  Class::Accessor::Fast: 0
  File::Basename: 0
  Image::Size: 0
  List::Util: 0
  Module::Util: 0
  POE: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::Balloon: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  UNIVERSAL::require: 0
  aliased: 0
  perl: 5.010
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Games::Risk:
    file: lib/Games/Risk.pm
    version: 0.3.2
  Games::Risk::AI:
    file: lib/Games/Risk/AI.pm
  Games::Risk::AI::Dumb:
    file: lib/Games/Risk/AI/Dumb.pm
  Games::Risk::GUI:
    file: lib/Games/Risk/GUI.pm
  Games::Risk::GUI::Board:
    file: lib/Games/Risk/GUI/Board.pm
  Games::Risk::GUI::Invasion:
    file: lib/Games/Risk/GUI/Invasion.pm
  Games::Risk::Heap:
    file: lib/Games/Risk/Heap.pm
  Games::Risk::Map:
    file: lib/Games/Risk/Map.pm
  Games::Risk::Map::Continent:
    file: lib/Games/Risk/Map/Continent.pm
  Games::Risk::Map::Country:
    file: lib/Games/Risk/Map/Country.pm
  Games::Risk::Player:
    file: lib/Games/Risk/Player.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
