---
abstract: "classical 'risk' board game"
author:
  - 'Jerome Quelin'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.101151'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Risk
provides:
  Games::Risk:
    file: lib/Games/Risk.pm
    version: 3.101590
  Games::Risk::AI:
    file: lib/Games/Risk/AI.pm
    version: 3.101590
  Games::Risk::AI::Blitzkrieg:
    file: lib/Games/Risk/AI/Blitzkrieg.pm
    version: 3.101590
  Games::Risk::AI::Dumb:
    file: lib/Games/Risk/AI/Dumb.pm
    version: 3.101590
  Games::Risk::AI::Hegemon:
    file: lib/Games/Risk/AI/Hegemon.pm
    version: 3.101590
  Games::Risk::Card:
    file: lib/Games/Risk/Card.pm
    version: 3.101590
  Games::Risk::Continent:
    file: lib/Games/Risk/Continent.pm
    version: 3.101590
  Games::Risk::Controller:
    file: lib/Games/Risk/Controller.pm
    version: 3.101590
  Games::Risk::Country:
    file: lib/Games/Risk/Country.pm
    version: 3.101590
  Games::Risk::GUI:
    file: lib/Games/Risk/GUI.pm
    version: 3.101590
  Games::Risk::GUI::Board:
    file: lib/Games/Risk/GUI/Board.pm
    version: 3.101590
  Games::Risk::GUI::GameOver:
    file: lib/Games/Risk/GUI/GameOver.pm
    version: 3.101590
  Games::Risk::GUI::MoveArmies:
    file: lib/Games/Risk/GUI/MoveArmies.pm
    version: 3.101590
  Games::Risk::GUI::Startup:
    file: lib/Games/Risk/GUI/Startup.pm
    version: 3.101590
  Games::Risk::I18N:
    file: lib/Games/Risk/I18N.pm
    version: 3.101590
  Games::Risk::Map:
    file: lib/Games/Risk/Map.pm
    version: 3.101590
  Games::Risk::Player:
    file: lib/Games/Risk/Player.pm
    version: 3.101590
  Games::Risk::Resources:
    file: lib/Games/Risk/Resources.pm
    version: 3.101590
  Games::Risk::Tk::About:
    file: lib/Games/Risk/Tk/About.pm
    version: 3.101590
  Games::Risk::Tk::Cards:
    file: lib/Games/Risk/Tk/Cards.pm
    version: 3.101590
  Games::Risk::Tk::Continents:
    file: lib/Games/Risk/Tk/Continents.pm
    version: 3.101590
  Games::Risk::Tk::Help:
    file: lib/Games/Risk/Tk/Help.pm
    version: 3.101590
recommends: {}
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Encode: 0
  Exporter: 0
  File::Basename: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  FindBin: 0
  Image::Magick: 0
  Image::Size: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::TextDomain: 0
  MIME::Base64: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  MooseX::POE: 0
  MooseX::SemiAffordanceAccessor: 0
  POE: 0
  POE::Loop::Tk: 0
  Path::Class: 0
  Readonly: 0
  Sub::Exporter: 0
  Tk: 0
  Tk::Balloon: 0
  Tk::BrowseEntry: 0
  Tk::Font: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  Tk::Pane: 0
  Tk::Pod::Text: 0
  Tk::Role::Dialog: 1.101480
  Tk::Sugar: 0
  Tk::TableMatrix: 0
  UNIVERSAL::require: 0
  aliased: 0
  constant: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Games-Risk
  homepage: http://search.cpan.org/dist/Games-Risk/
  repository: http://github.com/jquelin/games-risk
version: 3.101590
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereq:
          phase: runtime
          type: requires
      name: Prereq
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.100740
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@JQUELIN/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.100690
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@JQUELIN/MetaTests'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@JQUELIN/PortabilityTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@JQUELIN/ReportVersions'
      version: 1.100880
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@JQUELIN/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@JQUELIN/AutoPrereq'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.100960
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.100701
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.11
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.10001919
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git/Check'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git/Commit'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/Git/Tag'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git/Push'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 2.101151
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 2.101151
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 2.101151
