--- #YAML:1.0
name:                Games-Risk
version:             2.0.3
abstract:            classical 'risk' board game
license:             gpl
author:              
    - Jerome Quelin, <jquelin@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    aliased:                       0
    Class::Accessor::Fast:         0
    File::Basename:                0
    Getopt::Euclid:                0
    Image::Resize:                 0
    Image::Size:                   0
    List::MoreUtils:               0
    List::Util:                    0
    MIME::Base64:                  0
    Module::Util:                  0
    POE:                           0
    Readonly:                      0
    Test::More:                    0
    Tk:                            0
    Tk::Balloon:                   0
    Tk::Font:                      0
    Tk::JPEG:                      0
    Tk::Pane:                      0
    Tk::PNG:                       0
    UNIVERSAL::require:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
