--- #YAML:1.0
name:               Games-Risk
version:            2.1.2
abstract:           classical 'risk' board game
author:
    - Jerome Quelin, <jquelin@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    aliased:              0
    Class::Accessor::Fast:  0
    File::Basename:       0
    File::Temp:           0
    Getopt::Euclid:       0
    Image::Imlib2:        0
    Image::Size:          0
    List::MoreUtils:      0
    List::Util:           0
    MIME::Base64:         0
    Module::Util:         0
    POE:                  0
    POE::Loop::Tk:        0
    Readonly:             0
    Test::More:           0
    Tk:                   0
    Tk::Balloon:          0
    Tk::Font:             0
    Tk::JPEG:             0
    Tk::Pane:             0
    Tk::PNG:              0
    UNIVERSAL::require:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
